apps/authentication/urls.py
from django.urls import path
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from apps.authentication.views import (RegistrationView, ConfirmSignUpView, UserProfileFormView,
                                       UserProfileView, UserProfileUpdate, AboutView, WelcomeView, TwoFactorToggleview, 
                                       TwoFactorAuthenticationView, VerifyPhone, ResendOTP, ToggleAccess, Mnemonicgenerator,
                                       PasswordResetView, PasswordResetConfirmView,PasswordResetFormView)
app_name = 'auth'
urlpatterns = [
    path('signup/', RegistrationView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', UserProfileFormView.as_view(), name='userprofile'),
    path('view_profile/', UserProfileView.as_view(), name='userprofileview'),
    path('user_profile_update/', UserProfileUpdate.as_view(),
         name='userprofileupdate'),
    path('phoneverify', VerifyPhone.as_view(), name='phoneverify'),
    path('email-confirmation/<uidb64>/<token>/', ConfirmSignUpView.as_view(
    ), name="email_confirmation"),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/',
         PasswordResetFormView.as_view(), name='password_reset_form'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password_change/', login_required(auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html', success_url='done')), name='password_change'),
    path('password_change/done/',
         (auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password_change_done.html')), name='password_change_done'),
    path('otp/', TwoFactorAuthenticationView.as_view(), name='otp'),
    path('resendotp', ResendOTP.as_view(), name='resendotp'),
    path('toggle2factor', TwoFactorToggleview.as_view(), name='toggle2factor'),
    path('toggleaccess/<slug:slug>/', ToggleAccess.as_view(), name='toggleaccess'),
    path('mnemonic_gen', Mnemonicgenerator.as_view(), name='mnemonicgen'),

]

psalm/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from apps.authentication.views import WelcomeView, AboutView, Update

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('', include('apps.coins.urls', namespace='apps.coins')),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('aboutus/', AboutView.as_view(), name='aboutus'),
    path('aboutus1/', TemplateView.as_view(template_name='aboutus1.html'), name='aboutus1'),
    path('update/', Update.as_view(), name='update'),
] + static(settings.MEDIA_URL,  document_root=settings.STATIC_ROOT)

apps/authentication/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.crypto import get_random_string
from django.utils.translation import ugettext_lazy as _
from django_unixdatetimefield import UnixDateTimeField
from django.contrib.auth.models import AbstractUser, User


class User(AbstractUser):
    first_name = models.CharField(max_length=200, blank=True, default="")
    last_name = models.CharField(max_length=200, blank=True, default="")
    phone_number = models.CharField(max_length=20, blank=True, default="")
    timestamp = UnixDateTimeField(auto_now=True)

    @property
    def unique_id(self):
        return self.first_name + self.timestamp


class UserProfile(models.Model):
    """User Profile"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    country = models.CharField(
        max_length=128, help_text='Country')
    state = models.CharField(
        max_length=128, help_text='State')
    city = models.CharField(
        max_length=128, help_text='City')
    address_line_1 = models.CharField(
        max_length=128, help_text='Home Address')
    address_line_2 = models.CharField(
        max_length=128, help_text='Apartment/Suite number')
    address_line_3 = models.CharField(
        max_length=128, help_text='Locality Name')
    pincode = models.CharField(
        max_length=128, null=False, help_text='Zipcode')

    def __str__(self):
        return self.user.email


class UserTwoFactor(models.Model):
    """ Two factor settings of User"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    two_factor_status = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email


class Passphrase(models.Model):
    """ Mnemonic passphrase for resetting password"""
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    word_list = models.CharField(max_length=500, blank=True, null=True)
    viewed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email

apps/authentication/forms.py
from django import forms
from django.forms import ModelForm
from django.core.exceptions import *
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import authenticate, get_user_model, password_validation

from .users import UserModel
from .users import UsernameField
from .models import UserProfile, UserTwoFactor
User = UserModel()


class RegistrationForm(UserCreationForm):
    """
    Form for registering a new user account.

    """
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))

    class Meta:
        model = User
        fields = (UsernameField(), 'email', 'first_name', 'last_name')

    def clean_username(self):
        username = self.cleaned_data.get('username', '').lower()
        if User.objects.filter(**{UsernameField(): username}).exists():
            raise forms.ValidationError(
                _('A user with that username already exists.'))

        return username

    def clean_email(self):
        """
        Validate that the supplied email address is unique for the
        site.

        """
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            raise forms.ValidationError(
                _("This email address is already in use. Please supply a different email address."))
        return self.cleaned_data['email']


class TwoFactorStatusForm(ModelForm):

    """
    Form for enabling/disabling two factor authentication.

    """
    class Meta:
        model = UserTwoFactor
        fields = ('two_factor_status',)


class PhoneUpdateForm(ModelForm):
    
    """
    Form for updating Mobile Number.

    """
    class Meta:
        model = User
        fields = ('phone_number',)

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['phone_number'].help_text = 'Enter your Mobile Number.'



class ResendActivationForm(forms.Form):
    required_css_class = 'required'
    email = forms.EmailField(label=_("E-mail"))


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        labels = {
            "address_line_1": "Home Address",
            "address_line_2": "Apartment/Suite number",
            "pincode":"zipcode",
        }
        fields = ('address_line_1', 'address_line_2','city', 'state','pincode', 'country' )

class PhraseCheckForm(forms.Form):
    word1 = forms.CharField(max_length=20, required=True)
    word2 = forms.CharField(max_length=20, required=True)
    word3 = forms.CharField(max_length=20, required=True)
    word4 = forms.CharField(max_length=20, required=True)
    
    def clean(self):
        cleaned_data = super(PhraseCheckForm, self).clean()
        word1 = cleaned_data.get('word1')
        word2 = cleaned_data.get('word2')
        word3 = cleaned_data.get('word3')
        word4 = cleaned_data.get('word4')
        if not word1 and not word2 and not word3 and not word4:
            raise forms.ValidationError('You have to write something!')

class ResetPasswordForm(forms.Form):
    """
    A form that lets a user change set their password without entering the old
    password
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    new_password1 = forms.CharField(
        label=_("New password"),
        widget=forms.PasswordInput,
        strip=False
    )
    new_password2 = forms.CharField(
        label=_("New password confirmation"),
        strip=False,
        widget=forms.PasswordInput,
    )


    def clean_new_password2(self):
        password1 = self.cleaned_data.get('new_password1')
        password2 = self.cleaned_data.get('new_password2')
        if password1 and password2:
            if password1 != password2:
                raise forms.ValidationError(
                    self.error_messages['password_mismatch'],
                    code='password_mismatch',
                )
        return password2

templates/authentication/email_verified.html
<!DOCTYPE html> {% load static %}
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
	<title>Hashcoin</title>
	<meta charset="utf-8">
	<!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
	<meta name="description" content="">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/animations.css' %}">
	<link rel="stylesheet" href="{% static 'css/crypto_custom.css' %}">
	<script src="{% static 'js/vendor/modernizr-2.6.2.min.js' %}"></script>
	<!--[if lt IE 9]>
		<script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
		<script src="{% static 'js/vendor/respond.min.js' %}"></script>
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<![endif]-->
</head>

<body>
	<!--[if lt IE 9]>
		<div class="bg-danger text-center">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/" class="highlight">upgrade your browser</a> to improve your experience.</div>
	<![endif]-->
	<div class="preloader">
		<div class="preloader_image"></div>
	</div>
	<section class="success-bg full-page">

		<div class="container">
			<div class="row">
				<div class="col-sm-10 text-center success-center white-font">
								<a href="./" class="logo top_logo top_offset_logo">
									<img src="{% static 'img/logo.png' %}" alt="" class="img-fluid">
								</a>

					{% if error %}
						<h2>Error</h2>
					{% else %}
						<h2 class="white-font">Success</h2>
                    {% endif %}
					<div class="">
                        {% if error %}
                            <h4>You followed an invalid link. Please check.</h4>
						{% else %}
							<h3 class="white-font">Successfully Verified. Now You can login with your credentials.</h3>
						{% endif %}
					</div>
					{% if not error %}
					<span>
						<br>click
						<a href="{% url 'auth:login' %}" class="success-href">Here</a> to login</span>
					{% endif %}
				</div>
			</div>
		</div>
	</section>


	<script src="{% static 'js/compressed.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

	<script src="{% static 'js/aos.js' %}"></script>
	<script>
		AOS.init();
	</script>
	<!-- Google Map Script -->
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTwYSMRGuTsmfl2z_zZDStYqMlKtrybxo"></script>

	<script src="{% static 'js/aos.js' %}"></script>
</body>

</html>

templates/authentication/logged_out.html
{% extends "admin/base_site.html" %}
{% load i18n %}

{% block breadcrumbs %}<div class="breadcrumbs"><a href="{% url 'admin:index' %}">{% trans 'Home' %}</a></div>{% endblock %}

{% block content %}

<p>{% trans "Thanks for spending some quality time with the Web site today." %}</p>

<p><a href="{% url 'admin:index' %}">{% trans 'Log in again' %}</a></p>

{% endblock %}

templates/authentication/login.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container-fluid login-bg">
    <div class="row p-0 pt-5 p-md-5 bg-cover">

					<div class="col-md-6 offset-md-3 text-center mb-5 p-md-5">
						<div class="col-12 text-center pb-5">
							<div class=" col-10 offset-1 col-md-6 offset-md-3 white-font ">
								<h1 class="">Login</h1>
								<div class="breadcrumbs-dark">
									<span>Home</span>
									<span>/</span>
									<a href="">
										<span>Login</span>
									</a>
								</div>
							</div>
						</div>
						<div id="form-error" style="color: red;">{{ form.non_field_errors }}</div>
						<form name="login-form" class="contact-form columns_padding_10" method="post" action="./">
							{% csrf_token %}

							<div class="col-12">
								{% for field in form %} {% if field.errors%}
								<div class="form-field-errors text-left col-sm-6 offset-sm-3 no-list" style="color: red;">
									{{ field.errors }}
									<span class="help no-list">{{ field.help_text|safe }}</span>
								</div>
								{% endif %}
								<div class="col-sm-12 text-justify">
									<div class="form-group bottommargin_0">
										{% if field.field.widget.input_type == 'password' %}
										<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control dark-blue-input"
										    placeholder="{{field.label}}" value=""> {% else %}
										<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control dark-blue-input"
										    placeholder="{{field.label}}" value="{{ field.value|default_if_none:''}}"> {% endif%}

									</div>
	
								</div>
								{% endfor %}
								<div class="col-12 text-center">

									<div class="g-recaptcha d-flex justify-content-center" data-theme="dark" data-sitekey="6LdEcUIUAAAAAOdzadXa7dD9wVAs-g-AtegbLlM0"></div>
								</div>

								<div align="center" class="col-12 mt-3">
									<div class="contact-form-submit topmargin_20">
										<button type="button" onclick="validateForm()" class="btn ex-now ">Login</button>
									</div>
								</div>
						</form>
						<a href="{% url 'auth:password_reset'%}" class="white-font">Forgot password?</a>
						</div>
					


		</div>

	</div>
	<script type="text/javascript">
		function validateForm() {
			var recaptcha = document.forms["login-form"]["g-recaptcha-response"].value;
			if (recaptcha == "") {
				$("#form-error").text("Recaptcha Failed");
			} else {
				$("form").submit();
			}
		}
	</script>
	{% endblock %}

templates/authentication/mobile.html
{% extends 'base_signup.html' %} {% load static %} {% block content %}

<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ error }}</div>
				<form class="contact-form columns_padding_10" method="post" action="./">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="tel" size="30" value="" name="phone_number" id="id_phone_number"  class="form-control login-input" placeholder="Mobile Number">
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="button" onclick="sendData();" class="btn btn-secondary exchange-next">Send OTP</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>

{% endblock %}
{% block script %}
<script type="text/javascript">
    $("#id_phone_number").intlTelInput();
    function sendData(){
    	value = $("#id_phone_number").val()
    	$("#id_phone_number").intlTelInput("setNumber", "+"+$("#id_phone_number").intlTelInput("getSelectedCountryData").dialCode+value);
    	$("form").submit();
    }

</script>
{% endblock %}

templates/authentication/otp.html
{% extends 'base_signup.html' %} {% load static %} {% block content %}

<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ form.non_field_errors }}</div>
				<form class="contact-form columns_padding_10" method="post" action="./">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="text" size="30" value="" name="otp" id="id_otp" class="form-control login-input" placeholder="OTP">
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="submit" class="btn btn-secondary exchange-next ">Verify</button>
						</div>
					</div>
				</form>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
</section>

{% endblock %}

templates/authentication/password_change_done.html
{% extends "base_signup.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}

{% block content %}
<div class="col-12 text-center p-5">


    <h3>{% trans 'Your password is changed successfully.' %}</h3>
    <p>Please login with your new password</p>
    <div class="pb-5 text-center col-12 white-font mtb-auto">

        <a class="btn btn-secondary exchange-next" href="{% url 'auth:login' %}">Login</a>
    </div>
</div>
{% endblock %}

templates/authentication/password_reset.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">Password Reset</h1>
	<div class="breadcrumbs-dark">
		<span>Home</span>
		<span>/</span>
		<a href="">
			<span>Password Reset</span>
		</a>
	</div>
</div>
<section class="col-12">
	<div class="container">
		<div class="row mt-5">

			<div class="col-sm-6 offset-sm-3 text-center mt-5 mb-5">
				<div style="color: red;">{{ form.non_field_errors }}</div>
				<form class="pw-reset-form " method="post" id="pw-reset-form">
					{% csrf_token %}
					<div class="">
						<div class="form-group ">
							<input type="text" size="30" value="" name="email" id="id_email" class="form-control login-input" placeholder="email">
							<span>
								<p>{{form.email.errors}}</p>
							</span>
						</div>
					</div>
					<div align="center" class="">
						<div class="contact-form-submit topmargin_20">
							<button type="submit" name="contact_submit" id="pwreset" class="btn btn-secondary exchange-next ">Reset Password</button>
						</div>
					</div>
				</form>
				<div class="col-6 offset-3 d-flex  justify-content-around mt-3">
					<a href="{% url 'auth:login'%}">Login</a>
					<span>&nbsp;|&nbsp;</span>
					<a href="{% url 'auth:signup' %}">Signup</a>
				</div>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->

	<!-- error modal -->
	<div class="modal fade col-12" id="error_modal" tabindex="-1" role="dialog" aria-labelledby="#{{ currency }}_modalTitle"
	 aria-hidden="true">
		<div class="modal-dialog modal-dialog-centered" role="document">
			<div class="modal-content text-center">
				<div class="d-none d-md-block modal-header text-center">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h3 class="modal-title text-capitalize" id="">
						Error </h3>
				</div>
				<div class="col-12 d-md-none">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
					<h5 class="modal-title text-capitalize" id="">
						Error</h5>

				</div>
				<div class="modal-body text-center">
					<span id="error_msg">

					</span>
				</div>
				<div class="modal-footer">
					<div class="col-12 text-center">
						<button class="btn btn-default" data-dismiss="modal" aria-label="Close">Cancel</button>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- error modal -->

	{% endblock %} {% block script %}
	<script>
		$('#pwreset').click(function (e) {
			e.preventDefault();
			email = $("#id_email").val();
			if (email) {
				$.ajax({
					type: 'POST',
					url: "{% url 'auth:password_reset' %}",
					data: $('#pw-reset-form').serialize(),
					success: function (result) {
						if(result.success){
							window.location = "{% url 'auth:password_reset_confirm' %}";
						}
						else{
						$("#error_msg").html(result.error );
						$("#error_modal").modal("show");
						}
					},
					error: function (result) {
						$("#error_msg").text("An error occured. Please try again later. For assistance or grieviences contact support");
						$("#error_modal").modal("show");
	
					}
				});
			}
			else {
				$("#error_msg").text("Enter a valid email address");
				$("#error_modal").modal("show")
			}
		});
	</script> {% endblock %}

templates/authentication/password_reset_confirm.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="page-header-dark col-12">
	<h1 class="page-header-font-yellow">Password Reset</h1>
	<div class="breadcrumbs-dark">
		<span>Home</span>
		<span>/</span>
		<a href="">
			<span>Password Reset</span>
		</a>
	</div>
</div>
<section class="col-12">
	<div class="container">
		<div class="row mt-5">
			<h3>Remember those really cool words we asked you to write down when you first logged in, and we reminded you again and again
				never lose it? Now is the time to use it</h3>
			<div class="col-sm-6 offset-sm-3 text-center  mb-5">
				<div style="color: red;">{{ form.non_field_errors }}</div>
				<p>Confirm the words</p>
				<form class="col-12 p-0" id="confirm_wordlist" action="" method="POST">
					{% csrf_token %} {% for num,field in foo %}
					<div class="col-12 p-1  d-flex flex-row flex-wrap  align-items-center">
						<span class="col-4 col-md-2 px-0">Word {{num}}: </span>

						<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control col-8 col-md-10"
						 placeholder="Enter word {{num}}" value="">	
						<input type="text" name="num{{forloop.counter}}" class="invisible h-0" value="{{num}}">
					</div>{% endfor %}

					
					<input type="submit" class="col-12 btn  btn-secondary exchange-next mt-2" value="Submit">

				</form>


				<div class="col-6 offset-3 d-flex  justify-content-around mt-3">
					<a href="{% url 'auth:login'%}">Login</a>
					<span>&nbsp;|&nbsp;</span>
					<a href="{% url 'auth:signup' %}">Signup</a>
				</div>
			</div>
		</div>
		<!--.row -->
	</div>
	<!--.container -->
	{% endblock %} {% block script %}
	{% endblock %}

templates/authentication/password_reset_done.html
 {% extends 'base.html' %} {% load static %} {% block content %}

<div class="col-sm-12 text-center p-5">
	<h2>Password reset sent</h2>
</div>

<section class=" text-center">

	<div class="col-sm-6 offset-sm-3 text-justify">

		<p>
			We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive
			them shortly. If you don't receive an email, please make sure you've entered the address you registered with, and check
			your spam folder.
			<p>
	</div>
	<div class="pb-5 text-center col-12 white-font mtb-auto">

		<a class="btn btn-secondary exchange-next" href="{% url 'auth:login' %}">Login</a>
	</div>
</section>

{% endblock %}

templates/authentication/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'auth:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

templates/authentication/signup.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="col-12 pad0 slide-bg" style="background-image: url({% static 'images/newyork.jpg' %}); background-size: cover;
background-attachment: fixed;
background-position: center;
background-repeat: no-repeat;
background-size: cover; ">




	<section class="col-12 mt-5">
		<div class="container-fluid text-center">
			<div class="row pb-5">
				<form name="signup-form" class="col-sm-6 offset-sm-3 text-center contact-form  bg-transparent-cover"
				 method="post" action="./">
					<div class=" col-12  col-md-6 offset-md-3 white-font  ">
						<h1 class="">Sign up</h1>
						<div class="breadcrumbs-dark">
							<span>Home</span>
							<span>/</span>
							<a href="">
								<span>Sign up</span>
							</a>
						</div>
					</div>
					{% csrf_token %} {% for field in form %}
					<div class="col-12">
						{% if field.errors%}
						<div class="form-field-errors text-left col-sm-10 offset-sm-1 no-list" style="color: red;">
							{{ field.errors }}
							<span class="help no-list">{{ field.help_text|safe }}</span>
						</div>
						{% endif %}
						<div class="col-sm-10 offset-sm-1 text-justify">
							<div class="form-group bottommargin_0">
								{% if field.field.widget.input_type == 'password' %}
								<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control signup-input"
								 placeholder="{{field.label}}" value=""> {% elif field.field.widget.input_type == 'checkbox'%}
								<div class="row d-flex  justify-content-between align-items-center">
									<div class="col-9">
										<span>Enable Two 2Factor Authentication</span>
									</div>
									<div class="col-3">
										<label class="switch">
											<input type="checkbox" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control signup-input" placeholder="{{field.label}}"
											 value="{{ field.choice_value}}" {% if enable %}checked="checked" {% endif %}>
											<span class="slider round"></span>
										</label>
									</div>
								</div>

								{% else %}
								<input type="{{ field.field.widget.input_type }}" name="{{ field.html_name }}" id="{{field.id_for_label}}" class="form-control signup-input"
								 placeholder="{{field.label}}" value="{{ field.value|default_if_none:''}}"> {% endif%}

							</div>
							<!-- {% if field.help_text %}
					<p class="help ">{{ field.help_text|safe }}</p>
					{% endif %} -->
						</div>
					</div>

					{% endfor %}
					<div class="col-sm-10 offset-sm-1">
						<div class="form-group bottommargin_0">
							<div class="g-recaptcha d-flex justify-content-center" data-sitekey="6LdEcUIUAAAAAOdzadXa7dD9wVAs-g-AtegbLlM0"></div>
						</div>
					</div>
					<div class="col-sm-12 text-center">
						<button type="button" name="contact_submit" onclick="validateForm()" class="btn  btn-secondary exchange-next">Sign up</button>

					</div>
					<div class="col-sm-12 text-center">
						<a href="{% url 'auth:login' %}" class="mt-5 col-12 white-font">Already exist? Login</a>
					</div>
				</form>
			</div>
			<!--.row -->
		</div>
		<!--.container -->
	</section>
</div>
<script type="text/javascript">
	function validateForm() {
		var recaptcha = document.forms["signup-form"]["g-recaptcha-response"].value;
		if (recaptcha == "") {
			$("#form-error").text("Recaptcha Failed");
		} else {
			$("form").submit();
		}
	}
</script> {% endblock %}