apps/authentication/urls.py
from django.urls import path
from django.urls import reverse, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from apps.authentication.views import (RegistrationView, ConfirmSignUpView, UserProfileFormView,
                                       UserProfileView, UserProfileUpdate, AboutView, WelcomeView, TwoFactorToggleview, 
                                       TwoFactorAuthenticationView, VerifyPhone, ResendOTP, ToggleAccess, Mnemonicgenerator,
                                       PasswordResetView, PasswordResetConfirmView,PasswordResetFormView)
app_name = 'auth'
urlpatterns = [
    path('signup/', RegistrationView.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='authentication/login.html'),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/'), name='logout'),
    path('profile/', UserProfileFormView.as_view(), name='userprofile'),
    path('view_profile/', UserProfileView.as_view(), name='userprofileview'),
    path('user_profile_update/', UserProfileUpdate.as_view(),
         name='userprofileupdate'),
    path('phoneverify', VerifyPhone.as_view(), name='phoneverify'),
    path('email-confirmation/<uidb64>/<token>/', ConfirmSignUpView.as_view(
    ), name="email_confirmation"),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_confirm/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='authentication/password_reset_done.html'), name='password_reset_done'),
    path('reset/',
         PasswordResetFormView.as_view(), name='password_reset_form'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('password_change/', login_required(auth_views.PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html', success_url='done')), name='password_change'),
    path('password_change/done/',
         (auth_views.PasswordChangeDoneView.as_view(template_name='authentication/password_change_done.html')), name='password_change_done'),
    path('otp/', TwoFactorAuthenticationView.as_view(), name='otp'),
    path('resendotp', ResendOTP.as_view(), name='resendotp'),
    path('toggle2factor', TwoFactorToggleview.as_view(), name='toggle2factor'),
    path('toggleaccess/<slug:slug>/', ToggleAccess.as_view(), name='toggleaccess'),
    path('mnemonic_gen', Mnemonicgenerator.as_view(), name='mnemonicgen'),

]

apps/coins/urls.py
from django.urls import path, register_converter
from django.views.generic import TemplateView, FormView, View, ListView
from . views import IndexView, ExchangeRateView, ExchangeView, WalletsView, TransactionView, SendTransactionView,\
    SendConfirmView, TestView, VaultCoinView, TransactionPdfView, MyVault, VaultRetrieve, VaultRetrieveApprove,\
    AdminVaultRequestView, SystemStat,SystemStatUser, NewCoinAddr

from psalm import convertor
register_converter(convertor.PKConverter, 'slug')


app_name = 'coins'
urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('exchange/', ExchangeView.as_view(), name='exchange'),
    path('exchange-rate/', ExchangeRateView.as_view(), name='exchange_rate'),
    path('wallets/', WalletsView.as_view(), name='wallets'),
    path('newaddr/', NewCoinAddr.as_view(), name='newaddr'),
    path('transaction/', TransactionView.as_view(), name='transaction'),
    path('sendcoin/<slug:slug>/', SendTransactionView.as_view(), name='sendcoin'),
    path('sendconfirm/<slug:slug>/', SendConfirmView.as_view(), name='sendconfirm'),
    path('approve/', VaultRetrieveApprove.as_view(), name='vaultreqapprove'),
    path('vault/<slug:slug>/', VaultCoinView.as_view(), name='send2vault'),
    path('vault/retrieve/<slug:slug>/', VaultRetrieve.as_view(), name='retrievefromvault'),
    path('transactionpdf', TransactionPdfView.as_view(), name='transactionpdf'),
    path('myvault', MyVault.as_view(), name='myvault'),
    path('adminvaultrequest/', AdminVaultRequestView.as_view(), name='adminvaultrequest'),
    path('system_stat/', SystemStat.as_view(), name='systemstat'),
    path('system_user/<slug:slug>/', SystemStatUser.as_view(), name='systemstatuser'),
    path('test/', TestView.as_view(), name='test'),
]

psalm/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.contrib.auth.decorators import login_required

from apps.authentication.views import WelcomeView, AboutView, Update

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('apps.authentication.urls', namespace='auth')),
    path('', include('apps.coins.urls', namespace='apps.coins')),
    path('welcome/', WelcomeView.as_view(), name='welcome'),
    path('aboutus/', AboutView.as_view(), name='aboutus'),
    path('aboutus1/', TemplateView.as_view(template_name='aboutus1.html'), name='aboutus1'),
    path('update/', Update.as_view(), name='update'),
] + static(settings.MEDIA_URL,  document_root=settings.STATIC_ROOT)

templates/aboutus.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="col-12 p-0 pb-5 coverattached"  style="background-image: url({% static 'images/newyork.jpg' %}); background-size:cover;">

    <div class="page-header-dark col-12 bg-transparent-cover">
        <h1 class="page-header-font-yellow">Who We Are</h1>
        <div class="breadcrumbs-dark">
            <span>Home</span>
            <span>/</span>
            <a href="">
                <span>About US</span>
            </a>
        </div>
    </div>
    <div class="col-10 offset-1 mt-5 bg-transparent-cover white-font p-5">
        <div class="row text-justify">
            <h1>
                About Us</h1>
            <p>


                Psalm is not just a revolutionary exchange where investors from across the globe can trade cryptocurrency with ease. We are
                a complete non-banking financial digital institution giving community members complete control of their “money”
                and investment decisions. We are dedicated to bringing our real-life finance skills and expertise to our
                global user friendly community platform. As supply and demand are created with opportunities to digitize
                common everyday assets, more cryptocurrency will be designed to monetize profits for our community.

            </p>

            <h1>Corporate Vision</h1>
            <p>The vision of our platform is different; we are focused on building a community non-bank for the blockchain era,
                which will eventually become a one-stop shop for all financial services. Brick and mortar banks have become
                just institutions with very little depositor transparency, “fine print” with increasing regulations, high
                fees to access your capital, increased penalties, and monthly account service fees. As a digitize virtual
                community non-bank financial institution, we will be able to take back control of our money. We are dedicated
                to bringing our real-life finance skills and expertise to our global user friendly community platform. As
                supply and demand are created with opportunities to digitize common everyday assets, more cryptocurrency
                will be designed to monetize profits for our community members. We will become a top cryptocurrency fintech
                non-banking company in the world in the next 3 years

            </p>
        </div>
    </div>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html> {% load static %}

<html>

<head>
    <title>Psalm</title>
    <meta charset="utf-8">
    <!--[if IE]>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<![endif]-->
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon/favicon.ico' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fonts.css' %}">
    <link rel="stylesheet" href="{% static 'css/crypto_custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/theme.css' %}">
    <link rel="stylesheet" href="{% static 'css/intlTelInput.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> {% block style %} {% endblock style %}

    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro" rel="stylesheet">
    <style>
        .preload {
            width: 100%;
            height: 100%;
            position: fixed;
            z-index: 9999;
            background:url("{% static '/images/bitcoin.gif' %}") no-repeat center center rgba(255,
            255,
            255,
            1);
        }
    </style>
    <!--[if lt IE 9]>
		<script src="{% static 'js/vendor/html5shiv.min.js' %}"></script>
		<script src="{% static 'js/vendor/respond.min.js' %}"></script>
		<script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
	<![endif]-->
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>

<body>
    <div class="preload">
    </div>
    {% if messages %}
    <div class="django-message-alert ">
        {% for message in messages %}

        <script>

            window.setTimeout(function () {
                $.notify({
                    icon: 'fa fa-warning-sign',
                    title: '',
                    message: "{{ message }}"
                }, {
                        animate: {
                            enter: 'animated fadeInRight',
                            exit: 'animated fadeOutRight'
                        },

                        type: '{{ message.tags }}'

                    });
            }, {{ forloop.counter }}000);
        </script> {% endfor %}
    </div>
    {% endif %}
    <div class="white-font bg-blue p-3 d-md-flex justify-content-around">
        <div class="col-md-3  ">
            <a href="{% url 'coins:home' %}">
                <span class="logo-font d-flex align-items-center">
                    <img src="{% static 'images/theme/Logo.png' %}" class=" logo img-fluid"> &nbsp; Psalm</span>
            </a>
        </div>
        <div class="col-md-3 d-flex flex-row justify-content-around">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ request.user.first_name}}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right " aria-labelledby="userMenu">
                        <a class="dropdown-item" href="{% url 'coins:wallets' %}">Wallet</a>
                        <a class="dropdown-item" href="">Transactions</a>
                        {% if user.is_superuser %}
                        <a class="dropdown-item" href="{% url 'coins:adminvaultrequest' %}">Vault</a>
                        <a class="dropdown-item" href="{% url 'coins:systemstat' %}">System Status</a>
                        {% endif %}
                        <a class="dropdown-item" href="{% url 'auth:password_change' %}">Change password</a>
                        <a class="dropdown-item" href="{% url 'auth:userprofileview' %}">Profile</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="/auth/logout/">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <a class="nav-item nav-link" href="/auth/login/">
                <span class="white-font bit-font">
                    <i class="fa fa-user "> </i> LOGIN</span>
            </a>
            <a class="nav-item nav-link " href="/auth/signup/">
                <span class="white-font bit-font">
                    <i class="fa fa-sign-in "> </i> SIGNUP</span>
            </a>


            {% endif %}
        </div>
    </div>
    <nav class="navbar navbar-expand-lg nav-darkblue crypto-nav sticky-top">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="fa fa-bars" aria-hidden="true"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarNavAltMarkup">
            <div class="navbar-nav text-uppercase mr-auto">
                <a class="nav-item nav-link active" href="{% url 'coins:home' %}">home</a>
                <a class="nav-item nav-link" href="{% url 'aboutus' %}">About Us</a>
                <a class="nav-item nav-link" href="{% url 'coins:exchange' %}">Exchange</a>
                {% if user.is_authenticated %}
                <a class="nav-item nav-link " href="{% url 'coins:wallets' %}">Wallet</a>
                <a class="nav-item nav-link " href="{% url 'coins:transaction' %}">Transactions</a>
                {% endif %}



            </div>

        </div>
    </nav>
    <div class="font-darkgrey">
        <!-- section caraousel-->

        {% block carousel%} {% endblock carousel %} {% block content_wallet %} {% endblock content_wallet %}
        <!-- end caraousel -->
        {% block wallet_content %} {% endblock wallet_content%}
        <div class="container-fluid">
            <div class="row">
                {% block content %} {% endblock content%}
            </div>
        </div>
        <!-- section about bitcoin -->
    </div>
    <section class=" footer">
        <div class=" bg-black p-5">
            <div class="col-12 p-3">
                <span>Access your Bitcoin Wallet securely</span>
            </div>
            <div class="col-12 p-3">
                <span class="footer-bold sansthick">Psalm on all your devices</span>
            </div>
            <div class="col-12 p-3">
                <img class="img-fluid mt-1" src="{% static 'images/theme/appstore.png' %}">
                <img class="img-fluid mt-1" src="{% static 'images/theme/playstore.png'%}">
            </div>
        </div>
        <div class=" p-5 bg-navyblue">
            <div class="row col-md-10 offset-md-1 text-left">



                <div class="col-12 p-3 text-center">
                    <span class="footer-header">Contact Us</span>
                    <!-- underline -->
                    <div class="col-12 d-flex justify-content-center">
                        <div class="col-3 col-md-2 d-flex align-items-center justify-content-end">
                            <div class="col-9 push-3 line-1"></div>
                        </div>
                        <img class="" src="{% static 'images/theme/rectangle.png' %}">
                        <div class="col-3 col-md-2 d-flex align-items-center justify-content-start">
                            <div class="col-9 push-3 line-1"></div>
                        </div>
                    </div>
                    <!-- underline -->
                    <div class="mt-3 d-flex justify-content-around flex-wrap">
                       <!-- <a href="#">info@Coinzel.net</a>
                        <a href="#">press@coinzel.net </a> !-->
                        <a href="#">contact@psalm.io</a>
                        <!-- <a href="#">complaints@coinzel.net </a>
                        <a href="#">+44 20 8133 5474</a>!-->
                    </div>
                </div>



            </div>
        </div>



    </section>

    <div class="p-3 p-sm-0 d-flex  justify-content-around align-items-center bg-lightblue container-fluid">
        <div class="row col-12 d-flex  justify-content-around align-items-center">

            <div class="col-12 col-md-4 mt-2">
                <div class="col-12 col-sm-8 offset-sm-2  d-flex justify-content-around align-items-center p-2">
                    <div class="fsc">
                        <i class="fa fa-facebook p-2" aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-twitter  p-2" aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-linkedin p-2 " aria-hidden="true"></i>
                    </div>
                    <div class="fsc">
                        <i class="fa fa-github  p-2" aria-hidden="true"></i>
                    </div>
                </div>

            </div>
            <div class="col-12 col-md-4 mt-2 text-center">
                <span class=" white-font sansthick">Copyright by Psalm ltd {% now "Y" %}.
                </span>
            </div>
            <div class="col-12 col-md-4 mt-2 text-center">
                <span class="margin-center">
                    <img class="img-fluid" src="{% static 'images/theme/bankicons.png' %}">
                </span>
            </div>
        </div>

    </div>


    <!-- script -->
    <script src="{% static 'js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.js' %}"></script>
    <script src="{% static 'js/bootstrap-select.js' %}"></script>
    <script src="{% static 'js/custom_crypto.js' %}"></script>
    <script src="{% static 'js/notify.js' %}"></script>
    <script src="{% static 'js/numeral.min.js' %}"></script>
    <script src="{% static 'js/locales.min.js' %}"></script>


    <script>// makes sure the whole site is loaded
        $(window).on('load', function () {
            $('.preload').delay(250).fadeOut('slow'); // will fade out the white DIV that covers the website.
        })
    </script>

    <script src="{% static 'js/intlTelInput.js' %}"></script> {% block script %} {% endblock script %}

</body>

</html>

templates/pay_in.html
{% extends 'base.html' %} {% load static %} {% block content %}
<section class="col-12">

			<div class="col-sm-6 offset-sm-3 text-center ">
				<img src="https://chart.googleapis.com/chart?chs=300x300&cht=qr&chl={{address}}"></img>
				<h3> Please pay to the following address from your wallet</h3>
				<h4>{{ address }}</h4>
            </div>

</section>
{% endblock %}

templates/send_coin.html
{% extends 'base.html' %} {% load static %} {% load transaction_status %} {% block style %} {% endblock style %} {% block wallet_content %}
<section class="section-blue wallet-wrapper container-fluid text-center">
    <div class="row">
        <div class="col-md-6 text-center white-font">

            <div class="col-12 d-flex justify-content-center align-items-center">
                <img src="/static/images/coins/{{ currency }}.png" class="img-fluid img-80">
                <h1 class="d-inline-block text-uppercase white-font">{{ currency }}</h1>
            </div>
            <h1>Recipient Address</h1>
            <div class="col-12 col-md-10 offset-md-1 mt-3">
                <textarea type="text" class="wallet-send-coin-addr" placeholder="Enter the recipient wallet address"></textarea>
            </div>

            <h1>Amount to transfer</h1>
            <div class="col-12 col-md-10 offset-md-1 mt-3">
                <textarea type="text" class="wallet-send-coin-amt" placeholder="Enter the Amount to send"></textarea>
            </div>
        </div>

        <div class="col-md-6">
            <div class="col-12 d-flex justify-content-center align-items-center">
                <h1 class="d-inline-block text-uppercase white-font">Your {{ currency }} wallet details </h1>
            </div>

            <div class="bal-wrapper d-flex align-items-center flex-wrap col-10 offset-1">
                <div class="col-12 col-md-6 d-flex justify-content-start align-items-center">
                    <img src="/static/images/coins/{{ currency }}.png" class="img-fluid img-40">
                    <p class="d-inline-block text-uppercase">{{ currency }}</p>
                </div>
                <div class="col-12 col-md-6 float-left float-md-none">
                    <span class=" pull-right ">Bal: {% get_bal_coin currency request.user.username  %}</span>
                </div>
            </div>

          <!--   <div class="bal-wrapper d-flex align-items-center justify-content-between  flex-wrap col-10 offset-1">
                <span class="mr-auto">Estimated Mining fees : &emsp;</span>
                <span>0.00000</span> &nbsp;
                <span>BTC</span>
            </div>
            <div class="bal-wrapper d-flex align-items-center flex-wrap col-10 offset-1">
                <span class="mr-auto">Psalm Transaction : &emsp;</span>
                <span>0.00000</span> &nbsp;
                <span>BTC</span>
            </div>
            <div class="bal-wrapper d-flex align-items-center flex-wrap col-10 offset-1">
                <span class="mr-auto">Amount to send : &emsp;</span>
                <span>0.00000</span> &nbsp;
                <span>BTC</span>
            </div>
            <div class="bal-wrapper d-flex align-items-center flex-wrap col-10 offset-1">
                <span class="mr-auto">Balance after deduction : &emsp;</span>
                <span>0.00000</span> &nbsp;
                <span>BTC</span>
            </div> -->

            <!-- <div class="bal-wrapper d-flex align-items-center flex-wrap col-10 offset-1 h80 mt-3">
                <span class="mr-auto">Total Amount : &emsp;</span>
                <span class="font-weight-bold">0.00000</span> &nbsp;
                <span>{{ currency }}</span>
            </div> -->

        </div>
        <div class="col-12 text-center">
            <button href="#" onclick="send()" class="btn btn-send-coin mb-3">Confirm</button>
        </div>

<!-- modal -->

        <div class="modal fade col-12" id="confirm_Send" tabindex="-1" role="dialog" aria-labelledby="#{{ obj.name }}{{ forloop.counter}}Title"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content text-center">
                <div class="d-block modal-header text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title text-capitalize" id="{{ obj.name }}{{ forloop.counter}}LongTitle"> Confirm</h3>
                </div>
                <div class="modal-body text-center">
                    <span>Recipient Address: </span><span id="to_span"></span>
                    <br>
                    <span>Recipient recieves:</span><span id="amount_span">0.00000</span><span>{{ currency }}</span>
                    <br>
                    <!-- <span>Deduction from your account : </span><span>0.00000</span><span>BTC</span> -->
                   
                    <span>Confirm Transaction?</span>
                </div>
                <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" aria-label="Close">Cancel</button>
                    <button class="btn btn-info" onclick="sendConfirm()">Confirm</button>
                </div>
            </div>
        </div>
    </div>
<!-- endmodal -->
<!-- modal -->

    <div class="modal fade col-12" id="errorModal" tabindex="-1" role="dialog" aria-labelledby="#{{ obj.name }}{{ forloop.counter}}Title"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content text-center">
                <div class="d-block modal-header text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title text-capitalize" id="{{ obj.name }}{{ forloop.counter}}LongTitle"> Error</h3>
                </div>
                <div class="modal-body text-center">
                    <span id="errorDetails">Please enter the required fields.</span>

                </div>
                <div class="modal-footer">
                        <button class="btn btn-default" data-dismiss="modal" aria-label="Close">Cancel</button>
                </div>
            </div>
        </div>
    </div>
<!-- endmodal -->
<!-- modal -->

    <div class="modal fade col-12" id="successModal" tabindex="-1" role="dialog" aria-labelledby="#{{ obj.name }}{{ forloop.counter}}Title"
        aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content text-center">
                <div class="d-block modal-header text-center">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title text-capitalize" id="{{ obj.name }}{{ forloop.counter}}LongTitle"> Success</h3>
                </div>
                <div class="modal-body text-center">
                    <span id="errorDetails">Successfully Sent</span>

                </div>
                <div class="modal-footer">
                    <button class="btn btn-info" onclick="window.location='{% url 'coins:wallets' %}'">Ok</button>
                </div>
            </div>
        </div>
    </div>
<!-- endmodal -->


    </div>
</section>
{% endblock wallet_content %}



{% block script %} 
<script type="text/javascript">
function send(){
    address = $(".wallet-send-coin-addr").val();
    amount = $(".wallet-send-coin-amt").val();
    if(!amount || !address){
        $("#errorModal").modal("show")
    }
    else{
        $.ajax({
            type: "POST",
            url: "{% url 'coins:sendcoin' currency %}",
            data: {
                'to': address,
                'amount': amount,
                csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            success: function (data) {
                if (data['success']) {
                        $("#to_span").text($(".wallet-send-coin-addr").val());
                        $("#amount_span").text($(".wallet-send-coin-amt").val());
                        $("#confirm_Send").modal("show");

                }else{
                    $("#errorDetails").text(data['error']);
                    $("#errorModal").modal("show");
                }
            }
        })
    }
}
function sendConfirm(){
    $("#confirm_Send").modal("hide");
    address = $(".wallet-send-coin-addr").val();
    amount = $(".wallet-send-coin-amt").val();
    $("#confirm_Send").modal("hide")
    $.ajax({
        type: "POST",
        url: "{% url 'coins:sendconfirm' currency %}",
        data: {
            'to': address,
            'amount': amount,
            csrfmiddlewaretoken: '{{ csrf_token }}',
        },
        success: function (data) {
            if (data['success']){
                $("#successModal").modal("show");
            }     
            else{
              $("#errorDetails").text(data['error']);
              $("#errorModal").modal("show");
           }
           $('#successModal').on('hidden.bs.modal', function (e) {
            location.reload();
          })
        }
    });
}
</script>
{% endblock script %}

templates/vault_list.html
{% extends 'base.html' %} {% load static %} {% load transaction_status %} {% block style %} {% endblock style %} 
{% block wallet_content %}

<section class="section-blue wallet-wrapper container-fluid text-center">
    <div class="row">
        <div class="col-md-6 offset-md-3 p-0 p-md-5">
            <div class="my-balance col-12">
                <h1 class="white-font">My Vault</h1>
                {% for obj in allvault %}
                <div class="col-12">
                    <div class="bal-wrapper d-flex align-items-center flex-wrap">
                        <div class="col-4 col-lg-6 col-xl-3 d-flex justify-content-around align-items-center">
                            <img src="{% static 'images/coins/' %}{{ obj.name }}.png" class="img-fluid img-40">
                            <p class="d-inline-block text-uppercase">{{ obj.name }}</p>
                        </div>
                        <div class="col-8 col-lg-6 col-xl-6 float-left float-md-none pl-0">
                            <span class=" pull-right ">Bal: {% get_vault_balance request.user.username obj.name %}</span>
                        </div>
                        <div class="col-5 col-lg-5 col-xl-3 p-1">
                            <a href="{% url 'coins:retrievefromvault' obj.name %}" class="btn btn-default wallet-receive" >
                                <i class="fa fa-shield"> </i> Retrieve</a>
                        </div>

                    </div>
                </div>



                {% endfor %}



            </div>
        </div>
</section>

{% endblock %} {% block script %} 

{% endblock %}